name: Build Examples (Windows)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-windows:
    name: Build Code Examples
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore GroupDocs.Conversion.LowCode.Examples.sln
      
    - name: Build solution
      run: dotnet build GroupDocs.Conversion.LowCode.Examples.sln --no-restore --configuration Release
      
    - name: List all projects
      run: |
        echo "=== All Projects in Solution ==="
        Get-ChildItem -Path "Examples" -Recurse -Filter "*.csproj" | ForEach-Object { $_.FullName } | Sort-Object
        echo "=== Total Projects ==="
        (Get-ChildItem -Path "Examples" -Recurse -Filter "*.csproj").Count 